<a href="https://colab.research.google.com/github/vaibhavbaswal95/PyTorch-Tutorials/blob/master/tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [13]:
x = torch.empty(5, 3)
print(x)

tensor([[1.3324e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [2.6312e+20, 1.3225e-08, 2.7081e+23],
        [8.4945e+20, 6.5926e-10, 1.3294e-08],
        [1.7091e-04, 2.0942e+23, 7.5649e+28]])


Construct a randomly initialized matrix:



In [14]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6237, 0.1476, 0.4351],
        [0.7246, 0.3185, 0.0056],
        [0.1992, 0.4812, 0.6263],
        [0.8410, 0.1434, 0.2312],
        [0.3441, 0.7698, 0.4999]])


Construct a matrix filled zeros and of dtype long:



In [15]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [16]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [19]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.0020, -0.5380,  1.5279],
        [-1.4217,  0.8251, -0.6177],
        [ 0.0674,  0.2483,  1.6345],
        [-0.2515, -1.1428,  0.4774],
        [-0.2526,  0.2287,  2.0022]])


Get its size:



In [20]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [21]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.3809,  0.0941,  2.4795],
        [-1.1392,  1.4694, -0.3905],
        [ 0.6328,  0.7679,  1.7907],
        [ 0.3051, -0.8566,  0.9756],
        [ 0.3249,  0.5848,  2.1370]])


Addition: syntax 2



In [22]:
print(torch.add(x, y))

tensor([[ 0.3809,  0.0941,  2.4795],
        [-1.1392,  1.4694, -0.3905],
        [ 0.6328,  0.7679,  1.7907],
        [ 0.3051, -0.8566,  0.9756],
        [ 0.3249,  0.5848,  2.1370]])


Addition: providing an output tensor as argument



In [23]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3809,  0.0941,  2.4795],
        [-1.1392,  1.4694, -0.3905],
        [ 0.6328,  0.7679,  1.7907],
        [ 0.3051, -0.8566,  0.9756],
        [ 0.3249,  0.5848,  2.1370]])


Addition: in-place



In [24]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.3809,  0.0941,  2.4795],
        [-1.1392,  1.4694, -0.3905],
        [ 0.6328,  0.7679,  1.7907],
        [ 0.3051, -0.8566,  0.9756],
        [ 0.3249,  0.5848,  2.1370]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [25]:
print(x[:, 1])

tensor([-0.5380,  0.8251,  0.2483, -1.1428,  0.2287])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [26]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [34]:
x

tensor([[ 0.0929, -1.1051, -0.0049, -1.0808],
        [ 0.8687,  0.8901,  1.1510, -1.1772],
        [ 0.3653, -0.9786, -1.6455,  1.9554],
        [ 1.8644, -0.0924, -1.6693, -0.2484]])

In [36]:
x.view(8,-1)

tensor([[ 0.0929, -1.1051],
        [-0.0049, -1.0808],
        [ 0.8687,  0.8901],
        [ 1.1510, -1.1772],
        [ 0.3653, -0.9786],
        [-1.6455,  1.9554],
        [ 1.8644, -0.0924],
        [-1.6693, -0.2484]])

If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [37]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.9093])
0.9093039631843567


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [38]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [39]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [40]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [41]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [44]:
torch.cuda.is_available()

False